GRAVITY = -12
JUMP_SPEED = 2
BG_SCROLL_SPEED = 30
GROUND_SCROLL_SPEED = 2 * BG_SCROLL_SPEED
PIPE_SCROLL_SPEED = GROUND_SCROLL_SPEED
BG_LOOP_POINT = 413
REFRESH_RATE = 1 / 120.0
GAP_HEIGHT = 120
PIPE_HEIGHT_VARY = 20
BB_OFFSET = 2
GROUND_HEIGHT = 15

TITLE_STATE = 'title'
PLAY_STATE = 'play'
SCORE_STATE = 'score'

FLAPPY_FONT = '04b_19'
SMALL_FONT = '04b03'
SMALL_SIZE = 8
MEDIUM_SIZE = 14
FLAPPY_SIZE = 28
HUGE_SIZE = 56
